### ISSUE TITLE
how can i download all the books in the database?

### ISSUE THREAD

**Issue by rxmmah** [NYULibraries/aco-karms#523]
i need it for my AI model.

**Comment by ckassel** [comment]
Here are a couple of files that provide links to the PDF files. Hope this helps!
[ACO PDF links.csv](https://github.com/NYULibraries/aco-karms/files/13854293/ACO.PDF.links.csv)
[ACO PDF links.json](https://github.com/NYULibraries/aco-karms/files/13854294/ACO.PDF.links.json)
